name: Build & Deploy backend to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: planilla-ys-cr   # <-- nombre EXACTO del App Service de backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20 LTS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Instalar dependencias SOLO del backend
      - name: Install backend deps
        working-directory: backend
        run: npm ci

      # Empaquetar SOLO el backend para desplegar
      - name: Prepare artifact
        run: |
          mkdir -p release
          cp -R backend/* release/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: release

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-artifact
          path: .

      - name: Login to Azure using publish profile
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
