name: Build & Deploy backend to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: planilla-ys-cr   # <-- nombre EXACTO del App Service de backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20 LTS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # (Opcional) Instalar deps sólo para comprobar que el backend resuelve
      - name: Install backend deps
        working-directory: backend
        run: npm ci

      # ⬇️ Sube como artefacto DIRECTAMENTE la carpeta backend (sin node_modules si prefieres quitar el paso anterior)
      - name: Upload artifact (backend folder)
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-artifact
          path: .

      # ⬇️ Publica la carpeta backend (aquí sí existe package.json en ./backend)
      - name: Deploy to Azure Web App (publish profile)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: backend

